### ISSUE TITLE
error github backup

### ISSUE THREAD

**Issue by robnagler** [biviosoftware/utilities#7]
This has been happening for a few days. Not clear what it is, because the [cascaded errors are wrong](https://github.com/kennethreitz/requests/issues/1915).

```
Traceback (most recent call last):
  File "/home/github-bkp/Envs/env1/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 319, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/github-bkp/Envs/env1/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 493, in urlopen
    body=body, headers=headers)
  File "/home/github-bkp/Envs/env1/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 321, in _make_request
    httplib_response = conn.getresponse()
  File "/home/github-bkp/.pyenv/versions/3.4.1/lib/python3.4/http/client.py", line 1172, in getresponse
    response.begin()
  File "/home/github-bkp/.pyenv/versions/3.4.1/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/home/github-bkp/.pyenv/versions/3.4.1/lib/python3.4/http/client.py", line 321, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/github-bkp/Envs/env1/lib/python3.4/site-packages/requests/adapters.py", line 327, in send
    timeout=timeout
  File "/home/github-bkp/Envs/env1/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 543, in urlopen
    raise MaxRetryError(self, url, e)
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/radiasoft/rslinac/issues/53/events?per_page=100 (Caused by <class 'http.client.BadStatusLine'>: '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/github-bkp/src/biviosoftware/utilities/bin/github", line 142, in _repo
    _json(_Iterator(repo.iter_issues(state="all")), ".issues")
  File "/home/github-bkp/src/biviosoftware/utilities/bin/github", line 120, in _json
    j = i.to_json()
  File "/home/github-bkp/src/biviosoftware/utilities/bin/github", line 181, in to_json
    v = ",".join(map(_json, func()))
  File "/home/github-bkp/Envs/env1/lib/python3.4/site-packages/github3/structs.py", line 59, in __iter__
    headers=headers)
  File "/home/github-bkp/Envs/env1/lib/python3.4/site-packages/github3/models.py", line 130, in _get
    return self._session.get(url, **kwargs)
  File "/home/github-bkp/Envs/env1/lib/python3.4/site-packages/requests/sessions.py", line 468, in get
    return self.request('GET', url, **kwargs)
  File "/home/github-bkp/Envs/env1/lib/python3.4/site-packages/github3/session.py", line 81, in request
    response = super(GitHubSession, self).request(*args, **kwargs)
  File "/home/github-bkp/Envs/env1/lib/python3.4/site-packages/requests/sessions.py", line 456, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/github-bkp/Envs/env1/lib/python3.4/site-packages/requests/sessions.py", line 559, in send
    r = adapter.send(request, **kwargs)
  File "/home/github-bkp/Envs/env1/lib/python3.4/site-packages/requests/adapters.py", line 375, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/radiasoft/rslinac/issues/53/events?per_page=100 (Caused by <class 'http.client.BadStatusLine'>: '')
```

**Comment by robnagler** [comment]
Added 120 seconds between repos and didn't get the error. Changed to 60 seconds, because took to long. There are 150 repos (could be trimmed).
